version: '3'

services:
   
  
    mysql-server:
        image:                   mysql:5.7
        hostname:                mysql-server
        environment:
            MYSQL_ROOT_PASSWORD: userpass
            TZ:                  America/Argentina/Buenos_Aires
        volumes:
            -                    ./db/dumps:/docker-entrypoint-initdb.d
            -                    ./db/data:/var/lib/mysql
            -                    /etc/timezone:/etc/timezone:ro
            -                    /etc/localtime:/etc/localtime:ro

        networks:
            -                    NurseSystem-net

    mysql-admin:
        image:                   phpmyadmin/phpmyadmin
        environment: 
            PMA_HOST:            mysql-server
            PMA_PORT:            3306
            MYSQL_ROOT_PASSWORD: userpass
            TZ:                  America/Argentina/Buenos_Aires

        volumes:
            -                    /etc/timezone:/etc/timezone:ro
            -                    /etc/localtime:/etc/localtime:ro

        networks:
            -                    NurseSystem-net
        depends_on:
            -                    mysql-server
        ports:
            -                    "8001:80"

    node-backend:
        image:                   abassi/nodejs-server:10.0-dev
        volumes:
            -                    ./src/backend:/home/node/app/src   
            -                    /etc/localtime:/etc/localtime:ro
            -                    /etc/timezone:/etc/timezone:ro                  
        networks:
            -                    NurseSystem-net
        depends_on:
            -                    mysql-admin
        env_file:
            -                    .env                           
        
        ports: 
            -                    "8000:3000"
        command:                 bash -c " npm install node@12.22.12 &&sleep 50 && npm set registry https://registry.npmjs.org/ &&
                                 npm install --save randomstring cookie-parser dotenv@10.0.0 mqtt bcrypt express-jwt jsonwebtoken@8.5.1 node-schedule --save &&
                                 npm config set engine-strict true
                                 npm audit fix && 
                                 sleep 50  && 
                                 nodemon /home/node/app/src/index.js "
    

networks:
    NurseSystem-net:
        driver:                  bridge
