version: '3'

services:


   # mosquitto:
   #     container_name: mqtt
   #     image: eclipse-mosquitto
   #     network_mode: host
   #     ports:
   #     - 1883:1883
   #     - 9001:9001
   #     volumes:
   ##     - ./mosquitto/conf:/mosquitto/conf
   #     - ./mosquitto/data:/mosquitto/data
   #     - ./mosquitto/log:/mosquitto/log
   #     restart: unless-stopped


    mysql-server:
        platform: linux/x86_64
        image:                   mysql:5.7
        hostname:                mysql-server
        restart:                 always
        environment:
            MYSQL_ROOT_PASSWORD: userpass
        volumes:
            -                    ./db/dumps:/docker-entrypoint-initdb.d
            -                    ./db/data:/var/lib/mysql :rw                      
        
        ports:
            -                    '3306:3306'  
        expose:
            -                    '3306'
        user:                     mysql 
        networks:
            -                    NurseSystem-net

    mysql-admin:
        image:                   phpmyadmin/phpmyadmin
        environment: 
            PMA_HOST:            mysql-server
            PMA_PORT:            3306
            MYSQL_ROOT_PASSWORD: userpass
        networks:
            -                    NurseSystem-net
        depends_on:
            -                    mysql-server
        ports:
            -                    "8001:80"

    node-backend:
        image:                   abassi/nodejs-server:10.0-dev
        volumes:
            -                    ./src/backend:/home/node/app/src            
        networks:
            -                    NurseSystem-net
        depends_on:
            -                    mysql-admin
            -                    mysql-server
        ports: 
            -                    "8000:3000"
            -                    "9001:9001"
        command:                 bash -c "cd /home/node/app/src && npm install --force  && sleep 50  && nodemon /home/node/app/src/index.js"

networks:
    NurseSystem-net:
        driver:                  bridge
